### PR TITLE
Replace deprecated gulp-util

### PR DESCRIPTION
**Pull request by woneob**
[gulp-util](https://github.com/gulpjs/gulp-util) is deprecated:

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
```

### CODE REVIEW

**Comment by jon49** [comment]
Didn't notice this before. Merged!

**Comment by woneob** [comment]
@jon49 Thanks for merge this PR, but you didn't yet release a new version to npm.  
Can you bump and release?

**Comment by jon49** [comment]
I bumped. Can I add you as a package maintainer. Then you can update it directly. I don't spend much time in the JS world anymore.

**Comment by jon49** [comment]
What's your npm user name?

**Comment by woneob** [comment]
@jon49 No problem. My npm account name is "woneob"

**Comment by jon49** [comment]
You've been added as a maintainer.

**Comment by woneob** [comment]
I published 0.0.4 to npm. Thanks for adding me.

**Pull request merged**
